CREATE TABLE `salesforce_data` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VALUE` text NOT NULL,
  `URL` varchar(200) NOT NULL,
  `HAS_SYNC` int(1) NOT NULL,
  `FROM` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HAS_SYNC` (`HAS_SYNC`),
  KEY `CREATE` (`CREATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
